/**
 * Design System Refactor Radar — Example configuration
 *
 * This file is auto-generated by `npx design-system-refactor-radar init`.
 * You can also copy it manually and customize it.
 *
 * Run the interactive wizard: `npx design-system-refactor-radar init`
 * Or create this file manually and run: `npx design-system-refactor-radar init --no-interactive`
 *
 * All values below are examples — customize patterns to match YOUR design system.
 * @type {import('design-system-refactor-radar/config').DsCoverageConfig}
 */
export default {
  // ─── What to scan ────────────────────────────────────────
  scanDir: "src", // Single directory (backward compatible)
  // scanDirs: ["app", "components"], // Multiple directories (Next.js example)
  extensions: [".tsx", ".jsx", ".ts", ".js"],
  exclude: [
    "node_modules/",
    "dist/",
    "build/",
    "test/",
    "__tests__/",
    ".test.",
    ".spec.",
    "stories/",
    ".storybook/",
  ],

  // ─── Violation categories ────────────────────────────────
  //
  // Each category defines a regex pattern to detect hardcoded values.
  // Customize these patterns to match YOUR CSS methodology:
  //
  // Tailwind:     "bg-gray-500", "text-sm", "rounded-lg"
  // CSS Modules:  "#ff0000", "font-size: 14px"
  // CSS-in-JS:    "color: '#ff0000'", "fontSize: 14"
  // Vanilla CSS:  "#ff0000", "font-size: 14px"
  //
  violations: {
    // Example: Tailwind hardcoded colors
    // colors: {
    //   enabled: true,
    //   label: "Colors",
    //   icon: "🎨",
    //   color: "oklch(0.637 0.237 25.331)",
    //   pattern: "(?:bg|text|border|ring)-(?:gray|red|blue|green)-\\d+",
    // },

    // Example: CSS hardcoded colors
    // colors: {
    //   enabled: true,
    //   label: "Colors",
    //   icon: "🎨",
    //   color: "oklch(0.637 0.237 25.331)",
    //   pattern: "#[0-9a-fA-F]{3,8}\\b|\\brgba?\\s*\\(|\\bhsla?\\s*\\(",
    // },

    // Example: Typography
    // typography: {
    //   enabled: true,
    //   label: "Typography",
    //   icon: "🔤",
    //   color: "oklch(0.723 0.22 70.08)",
    //   pattern: "font-size\\s*:\\s*\\d+px",
    //   deduplicateByLine: true,
    // },
  },

  // ─── Migration flags ─────────────────────────────────────
  flags: {
    migrateSimple: "@ds-migrate:\\s*simple",
    migrateComplex: "@ds-migrate:\\s*complex",
    todo: "@ds-todo",
  },

  // ─── Component API analysis ──────────────────────────────
  componentAnalysis: {
    enabled: true,
    directories: ["components"],
    primaryDirectory: "components",
    legacyDirectories: [],
    api: {
      requireCVA: false,
      requireRadix: false,
      expectedProps: ["variant", "size"],
      forbiddenProps: [],
      expectedSizes: ["small", "medium", "large"],
      forbiddenSizes: [],
      legacyVariantValues: [],
    },
    scoring: {
      usesCVA: 0,
      correctNaming: 35,
      correctSizes: 25,
      hasClassName: 15,
      usesCompoundVariants: 0,
      hasAsChild: 0,
      usesRadix: 0,
    },
  },

  // ─── Roadmap phases ──────────────────────────────────────
  roadmap: {
    enabled: true,
    maxFilesPerPhase: 30,
    quickWinThreshold: 3,
    phases: [
      {
        id: "resolve-flags",
        title: "Resolve migration flags",
        description: "Files annotated with @ds-migrate from previous reviews.",
        businessCase: "Highest ROI — zero discovery cost, just execution.",
        filter: { type: "flags" },
      },
      {
        id: "quick-wins",
        title: "Quick wins — 1-3 violations",
        description: "Files that can be fully migrated with minimal effort.",
        businessCase: "Best coverage improvement per hour.",
        filter: { type: "quickWins" },
      },
    ],
  },

  // ─── Business Logic Analysis ───────────────────────────
  //
  // Detects business logic entanglement and native HTML elements
  // to help categorize refactoring risk (Safe/Careful/Page-level).
  //
  businessLogicAnalysis: {
    enabled: true,
    excludeDirectories: ["components/ui/"], // Exclude design system components
    riskThresholds: {
      safe: {
        maxStateHooks: 2,
        maxEffects: 0,
        maxApiCalls: 0,
      },
      careful: {
        maxStateHooks: 5,
        maxEffects: 2,
        maxApiCalls: 1,
      },
      // page-level = everything above careful thresholds
    },
    nativeHtmlElements: {
      enabled: true,
      elements: ["input", "select", "button", "label", "textarea", "form"],
    },
  },

  // ─── Import Boundary / Purity Analysis ──────────────────
  //
  // AST-based analysis to detect UI components entangled with business logic
  // through import boundary violations. Flags components that import
  // business logic zones, Next.js server APIs, or have transitive dependencies.
  //
  purity: {
    enabled: false, // Set to true to enable import boundary analysis
    // Directories containing UI components that should be "pure" (no business logic)
    uiCandidateDirs: ["components"],
    // Import patterns that are allowed in UI components
    allowedImportMatchers: [
      "react",
      "clsx",
      "classnames",
      "tailwind-merge",
      "@radix-ui/",
      "@/components/ui/",
    ],
    // Import patterns that indicate business logic entanglement
    forbiddenImportMatchers: [
      "@/lib/",
      "@/server/",
      "@/db/",
      "@/actions/",
      "@/features/",
    ],
    // Directory patterns that indicate business logic zones
    businessDirMatchers: [
      "app/",
      "lib/",
      "server/",
      "db/",
      "actions/",
      "features/",
    ],
    // Next.js server API imports that should be flagged
    nextServerImportMatchers: [
      "next/headers",
      "next/cache",
    ],
  },

  // ─── Component Migration Plan ───────────────────────────
  //
  // Define component mappings when migrating between libraries.
  // Each mapping declares source → target with complexity and guidelines.
  //
  migration: {
    enabled: false, // set to true to enable the Migration Plan tab
    targetDS: "shadcn/ui", // name of the target design system
    mappings: [],
  },

  // ─── Dashboard ───────────────────────────────────────────
  dashboard: {
    title: "Design System Refactor Radar",
    subtitle: "",
  },

  // ─── Output ──────────────────────────────────────────────
  output: {
    reportJson: "design-system-refactor-radar-report.json",
    dashboardHtml: "design-system-refactor-radar-dashboard.html",
  },
};
