/**
 * Template: Design System Compliance Skill
 *
 * Generates SKILL.md for Claude / Agents / Cursor skills.
 * References the generated rules and provides a quick summary.
 *
 * Fully agnostic — adapts to any CSS methodology and framework.
 */

import type { DsCoverageConfig } from "../config.js";

export function generateSkill(config: DsCoverageConfig): string {
  const api = config.componentAnalysis.api;
  const primaryDir = config.componentAnalysis.primaryDirectory;
  const hasComponentAnalysis = config.componentAnalysis.enabled;

  const enabledViolations = Object.entries(config.violations).filter(([, v]) => v.enabled);

  const violationSummary = enabledViolations
    .map(([, v]) => `${v.icon} ${v.label}`)
    .join(", ");

  const forbiddenSizesList = api.forbiddenSizes.length > 0
    ? api.forbiddenSizes.map((s) => `\`${s}\``).join(", ")
    : "";

  const componentSection = hasComponentAnalysis
    ? buildComponentSection(config)
    : "";

  return `---
name: design-system-compliance
description: Design system compliance protocol. Covers token enforcement, component creation standards, the Boy Scout Rule, and flagging conventions. Reference when building or modifying any frontend UI.
---

# Design System Compliance

> **Auto-generated by Design System Refactor Radar.** Re-run \`npx design-system-refactor-radar init\` to update.

**Load the rules:**
- \`.cursor/rules/design-system-compliance.mdc\` — Full compliance protocol
${hasComponentAnalysis ? "- `.cursor/rules/ui-component-creation.mdc` — Component creation standards" : ""}

---

## Protocol Summary

### CRITICAL — New code = design system only
**Every new line of UI code MUST use design system tokens and components. Zero tolerance for new hardcoded values.**

### Detected Violations
The scanner checks for: ${violationSummary || "No categories configured — edit design-system-refactor-radar.config.js"}
${componentSection}
### Boy Scout Rule
When editing a file in \`${config.scanDir}/\`:
1. **Apply simple migrations** on the code you touch — only when unambiguous
2. **Propose options** for ambiguous cases — provide visual context when possible
3. Flag complex migrations with \`@ds-migrate: complex\`
4. Flag missing components with \`@ds-todo\`
5. Never break existing behavior

### Flagging Conventions
\`\`\`
// @ds-migrate: simple | Swap hardcoded value → semantic token
// @ds-migrate: complex | Description. Risks: ... Cost: ... Constraint: ...
// @ds-todo: Create <ComponentName> — rationale
\`\`\`

### Scanner
Run \`npx design-system-refactor-radar\` to generate a coverage report and interactive dashboard.
Run \`npx design-system-refactor-radar --open\` to open the dashboard in the browser.
`;
}

// ============================================
// SECTION BUILDERS
// ============================================

function buildComponentSection(config: DsCoverageConfig): string {
  const api = config.componentAnalysis.api;
  const primaryDir = config.componentAnalysis.primaryDirectory;

  const propsLine = api.expectedProps.length > 0
    ? `- Variant props: ${api.expectedProps.map((p) => `**\`${p}\`**`).join(", ")}`
    : "";

  const sizesLine = api.expectedSizes.length > 0
    ? `- **\`size\`**: ${api.expectedSizes.map((s) => `\`${s}\``).join(", ")}`
    : "";

  const forbiddenSizesLine = api.forbiddenSizes.length > 0
    ? `- Forbidden legacy size values: ${api.forbiddenSizes.map((s) => `\`${s}\``).join(", ")} — use full words instead`
    : "";

  const forbiddenPropsLine = api.forbiddenProps.length > 0
    ? `- Forbidden legacy prop names: ${api.forbiddenProps.map((p) => `\`${p}\``).join(", ")}`
    : "";

  return `
### Component Decision Hierarchy
1. **Use an existing UI component** (\`${primaryDir}\`) — always check first
2. **Create a new UI component** in \`${primaryDir}\` — semantic tokens, simple name
3. **Inline with tokens** — last resort, flag if the pattern might repeat

### Component API Conventions
${propsLine}
${sizesLine}
- Always accept **\`className\`** for composition
${api.requireCVA ? "- Use **CVA** for variant management\n" : ""}${api.requireRadix ? "- Support **`asChild`** via Radix Slot\n" : ""}- Use **\`compoundVariants\`** for complex combinations
${forbiddenPropsLine}
${forbiddenSizesLine}
- Zero hardcoded colors — semantic tokens only
`;
}
